version: '3'
services:
  postgres:
    image: postgres
    ports:
      - '65435:5432'
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: testing
      POSTGRES_INITDB_ARGS: "-E=UTF8 --lc-collate=C --lc-ctype=C"